/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_learn_employee_EmployeeNativeApi */

#ifndef _Included_com_learn_employee_EmployeeNativeApi
#define _Included_com_learn_employee_EmployeeNativeApi
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_learn_employee_EmployeeNativeApi
 * Method:    getEmployee
 * Signature: (I)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_com_learn_employee_EmployeeNativeApi_getEmployee
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
