/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_learn_bridge_JNIExample */

#ifndef _Included_com_learn_bridge_JNIExample
#define _Included_com_learn_bridge_JNIExample
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_learn_bridge_JNIExample
 * Method:    sayHello
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_learn_bridge_JNIExample_sayHello
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
