/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_learn_add_Add */

#ifndef _Included_com_learn_add_Add
#define _Included_com_learn_add_Add
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_learn_add_Add
 * Method:    add
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_learn_add_Add_add
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
